# fontSettings
font_family       family="Jetbrains Mono"
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         10

# cursorSettings
cursor #12e0b0

# backgroundSettings
background_opacity 0.2
background_blur 1

# windowSettings
window_padding_width 2 10

# behaviorSettings
disable_ligatures never
inactive_text_alpha 1
allow_hyperlinks yes
# cursor_beam_thickness 9
url_style double
copy_on_select yes
