# Girl with cross
# preload = /home/saveon/Pictures/wallpaper/IMG_1465.PNG
# wallpaper = ,/home/saveon/Pictures/wallpaper/IMG_1465.PNG

# Dancing doe
# preload = /home/saveon/Pictures/wallpaper/wallhaven-5wx7x5.jpg
# wallpaper = ,/home/saveon/Pictures/wallpaper/wallhaven-5wx7x5.jpg

# Fish line
# preload = /home/saveon/Pictures/wallpaper/wallhaven-d6rzz3.png
# wallpaper = ,/home/saveon/Pictures/wallpaper/wallhaven-d6rzz3.png

# Fluffy whale
# preload = /home/saveon/Pictures/wallpaper/wallhaven-p9wm93.jpg 
# wallpaper = ,/home/saveon/Pictures/wallpaper/wallhaven-p9wm93.jpg 

# Checkpoint
# preload = /home/saveon/Pictures/wallpaper/wallhaven-l8zmor.jpg
# wallpaper = ,/home/saveon/Pictures/wallpaper/wallhaven-l8zmor.jpg

wallpaper {
    monitor = eDP-1
    path = /home/saveon/Pictures/wallpaper/wallhaven-l8zmor.jpg
    fit_mode = cover
}

#preload = /home/saveon/Pictures/wallpaper/*

# Settings
splash = false
ipc = true
