source = $HOME/.config/hypr/colors/teal-theme.conf

# utilityColor
$utility                = $teal_dim

# timeColor
$timeFontColor          = $teal_bright

# quoteColor
$quoteFontColor         = $teal_dim

# borderColor
$borderColor            = $teal

# inputColor
$inputFontColor         = $teal_text
$inputInnerColor        = $black_dim
$inputOuterColor        = $white

# shadowColor
$shadowColorBright      = $shadow_bright
$shadowColorDim         = $shadow_dim
$shadowComplement       = $shadow_com

# checkColor/failColor
$failColor       = $comp_bright 
$checkColor        = $teal_text
