# teal colorScheme

# backgrounds
$fg_dim         = rgb(a3cfc5)
$fg             = rgb(effffa)

# colors
$teal           = rgb(12e0b0)
$teal_dim       = rgb(0ba385)
$teal_bright    = rgb(a6ffe9)
$teal_text      = rgb(94e3db)
$complement_red = rgb(e01242)
$comp_bright    = rgb(224, 100, 18)

# darks/lights
$black_dim      = rgb(1a2422)
$white          = rgb(d7efec)

# shadows
$shadow_bright  = rgba(215, 239, 236, 0.4)
$shadow_dim     = rgba(166, 255, 233, 0.4)
$shadow_comp    = rgba(224, 100, 18, 0.4)

#tint
$tint           = rgb(0f201f)
